# Generated by Django 2.2 on 2020-06-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
